import 'package:firebase_core/firebase_core.dart';

/// Lightweight Firebase options placeholder used for the homework example.
///
/// Replace the placeholder values with the configuration generated by
/// `flutterfire configure` when connecting to a real Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: 'AIzaSyCAZ5EmkKq6xp9rt0EdCOKZr9yxd1khuWI',
        appId: '1:183514098272:android:715a20278a5a12e6eeb105',
        messagingSenderId: '183514098272',
        projectId: 'home-work-twelve-web-academy',
        storageBucket: 'home-work-twelve-web-academy.firebasestorage.app',
      );
}
